# Generated by Django 3.0.6 on 2021-06-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210608_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriemComission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=99999)),
            ],
            options={
                'verbose_name': 'Приёмная комиссия',
                'verbose_name_plural': 'Приемная комиссия',
            },
        ),
    ]
