# Generated by Django 3.0.6 on 2021-06-15 05:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_priemcomission'),
    ]

    operations = [
        migrations.CreateModel(
            name='S1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'СЕТЕВОЕ И СИСТЕМНОЕ АДМИНИСТРИРОВАНИЕ',
                'verbose_name_plural': 'СЕТЕВОЕ И СИСТЕМНОЕ АДМИНИСТРИРОВАНИЕ',
            },
        ),
        migrations.CreateModel(
            name='S2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'ПРОИЗВОДСТВО АВИАЦИОННЫХ ДВИГАТЕЛЕЙ',
                'verbose_name_plural': 'ПРОИЗВОДСТВО АВИАЦИОННЫХ ДВИГАТЕЛЕЙ',
            },
        ),
        migrations.CreateModel(
            name='S3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'ТЕХНОЛОГИЯ МАШИНОСТРОЕНИЯ',
                'verbose_name_plural': 'ТЕХНОЛОГИЯ МАШИНОСТРОЕНИЯ',
            },
        ),
        migrations.CreateModel(
            name='S4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'ИНФОРМАЦИОННЫЕ СИСТЕМЫ И ПРОГРАММИРОВАНИЕ',
                'verbose_name_plural': 'ИНФОРМАЦИОННЫЕ СИСТЕМЫ И ПРОГРАММИРОВАНИЕ',
            },
        ),
        migrations.CreateModel(
            name='S5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'ПРАВО И ОРГАНИЗАЦИЯ СОЦИАЛЬНОГО ОБЕСПЕЧЕНИЯ',
                'verbose_name_plural': 'ПРАВО И ОРГАНИЗАЦИЯ СОЦИАЛЬНОГО ОБЕСПЕЧЕНИЯ',
            },
        ),
        migrations.CreateModel(
            name='S6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'ЭЛЕКТРИЧЕСКИЕ СТАНЦИИ, СЕТИ И СИСТЕМЫ',
                'verbose_name_plural': 'ЭЛЕКТРИЧЕСКИЕ СТАНЦИИ, СЕТИ И СИСТЕМЫ',
            },
        ),
        migrations.CreateModel(
            name='S7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'ТЕХНОЛОГИЯ МЕТАЛЛООБРАБАТЫВАЮЩЕГО ПРОИЗВОДСТВА',
                'verbose_name_plural': 'ТЕХНОЛОГИЯ МЕТАЛЛООБРАБАТЫВАЮЩЕГО ПРОИЗВОДСТВА',
            },
        ),
    ]
