# Generated by Django 3.0.6 on 2021-06-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_s1_s2_s3_s4_s5_s6_s7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infooprieme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=99999)),
            ],
            options={
                'verbose_name': 'Информация о приеме',
                'verbose_name_plural': 'Информация о приеме',
            },
        ),
        migrations.CreateModel(
            name='Pravilapriema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=99999)),
            ],
            options={
                'verbose_name': 'Правила приёма',
                'verbose_name_plural': 'Правила приёма',
            },
        ),
        migrations.CreateModel(
            name='Prikazeozachislenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=99999)),
            ],
            options={
                'verbose_name': 'Приказы о зачислении',
                'verbose_name_plural': 'Приказы о зачислении',
            },
        ),
        migrations.CreateModel(
            name='Reitingoviespiske',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=99999)),
            ],
            options={
                'verbose_name': 'Рейтинговые списки',
                'verbose_name_plural': 'Рейтинговые списки',
            },
        ),
    ]
