# Generated by Django 3.0.6 on 2021-06-23 18:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_infooprieme_pravilapriema_prikazeozachislenie_reitingoviespiske'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infooprieme',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='pravilapriema',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='priemcomission',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='prikazeozachislenie',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='reitingoviespiske',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
