# Generated by Django 3.0.6 on 2021-06-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-create_time', '-id'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='news',
            name='create_time',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
