# Generated by Django 3.0.6 on 2021-06-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210623_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_time',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
