# Generated by Django 3.0.6 on 2021-06-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210623_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_time',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
