# Generated by Django 3.0.6 on 2021-06-23 19:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210623_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='instrtaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Электронная почта',
                'verbose_name_plural': 'Электронная почта',
            },
        ),
        migrations.CreateModel(
            name='instrtaction2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Электронная запись',
                'verbose_name_plural': 'Электронная запись',
            },
        ),
        migrations.CreateModel(
            name='instrtaction3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Почта России',
                'verbose_name_plural': 'Почта России',
            },
        ),
    ]
