# Generated by Django 3.0.6 on 2020-06-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('to', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
