# Generated by Django 3.0.6 on 2020-06-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SendDoc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsend',
            old_name='to',
            new_name='email',
        ),
    ]
