# Generated by Django 3.0.6 on 2020-06-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SendDoc', '0002_auto_20200617_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsend',
            options={'verbose_name': 'Встали в электронную очередь', 'verbose_name_plural': 'Встали в электронную очередь'},
        ),
        migrations.RemoveField(
            model_name='emailsend',
            name='name',
        ),
        migrations.RemoveField(
            model_name='emailsend',
            name='surname',
        ),
    ]
