# Generated by Django 3.0.6 on 2020-06-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendDoc', '0003_auto_20200619_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsend',
            name='date',
            field=models.DateTimeField(unique=True, verbose_name='Дата'),
        ),
    ]
