# Generated by Django 3.0.6 on 2020-06-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendDoc', '0004_auto_20200619_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsend',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
