# Generated by Django 3.0.6 on 2020-06-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendDoc', '0005_auto_20200619_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsend',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
