# Generated by Django 3.0.6 on 2020-06-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendDoc', '0006_auto_20200619_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsend',
            name='key',
            field=models.CharField(default=0, max_length=10, unique=True, verbose_name='Ключ'),
            preserve_default=False,
        ),
    ]
