# Generated by Django 3.0.6 on 2020-06-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendDoc', '0007_emailsend_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsend',
            name='key',
            field=models.CharField(max_length=10, verbose_name='Ключ'),
        ),
    ]
