# Generated by Django 3.0.6 on 2020-06-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendDoc', '0008_auto_20200619_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('date', models.DateTimeField(unique=True, verbose_name='Дата')),
                ('key', models.CharField(max_length=20, verbose_name='Ключ')),
                ('confirm', models.BooleanField(verbose_name='Подтверждение')),
            ],
            options={
                'verbose_name': 'Требуется подтверждение',
                'verbose_name_plural': 'Требуется подтверждение',
            },
        ),
        migrations.AlterField(
            model_name='emailsend',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='emailsend',
            name='key',
            field=models.CharField(max_length=20, verbose_name='Ключ'),
        ),
    ]
