# Generated by Django 3.0.6 on 2020-06-22 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SendDoc', '0009_auto_20200622_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='sent_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
    ]
