# Generated by Django 3.0.6 on 2021-05-25 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SendDoc', '0010_confirmation_sent_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmation',
            options={'verbose_name': 'Подтвержден?', 'verbose_name_plural': 'Подтвержден?'},
        ),
        migrations.RemoveField(
            model_name='confirmation',
            name='confirm',
        ),
    ]
